### ISSUE TITLE
cgi.FieldStorage fails due to missing LC_TYPE

### ISSUE THREAD

**Issue by dckc** [NuxiNL/cloudabi-ports#27]
To reproduce:

```
% cloudabi-run /usr/local/x86_64-unknown-cloudabi/bin/python3 < bug2.yaml
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "cgi.py", line 461, in __init__
  File "locale.py", line 639, in getpreferredencoding
NameError: name 'LC_CTYPE' is not defined
```

where `bug2.yaml` looks like:
```
%TAG ! tag:nuxi.nl,2015:cloudabi/
---
stderr: !fd stderr               # Let Python write backtraces to stderr.
path:
    - !file                      # Search path for Python modules.
      path: /usr/local/x86_64-unknown-cloudabi/lib/python3.6
command: >
    from sys import stderr; import cgi; from io import BytesIO;
    cgi.FieldStorage(fp=BytesIO(), environ={'QUERY_STRING': 'a=b'})
```

for my reference:
  https://github.com/dckc/ZeroVault/tree/cloudabi_wsgi 23fd185

**Comment by EdSchouten** [comment]
Hey! Thanks for reporting. I've just added a workaround for the absence of `setlocale()` to `locale.py` and fired up another package build. The package build should finish at some point during the night. I'll close this bug as soon as I've confirmed that the latest packages have been deployed.

**Comment by EdSchouten** [comment]
New packages have been deployed!
