### ISSUE TITLE
aarch64-unknown-cloudabi gmp fails to build on Ubuntu 15.10

### ISSUE THREAD

**Issue by moreati** [NuxiNL/cloudabi-ports#4]
I'm not sure if this is relevant or noteworthy. Please feel free to e.g. close it as wontfix.

On MacbookPro11,2 running Ubuntu 15.10 the following error occurs while building gmp

```
checking build system type... Invalid configuration `haswell-pc-linux-gnu': machine `haswell-pc' not recognized
```

The cause appears to be that gmp ships a [heavily customised](https://gmplib.org/repo/gmp-6.1/log/tip/config.sub)  `config.sub` & `config.guess`, which contain non-standard triplets. Hence when `config.sub` is replaced by `cloudabi-ports/misc/config.sub` the build scripts can't recognize the detected build system.

Full log/traceback

```
BUILD gmp
CHECKSUM /usr/cloudabi-ports/_obj/distfiles/gmp-6.1.0.tar.xz
[Errno 2] No such file or directory: '/usr/cloudabi-ports/_obj/distfiles/gmp-6.1.0.tar.xz'
FETCH http://ftp.gnu.org/gnu/gmp/gmp-6.1.0.tar.xz
CHECKSUM /usr/cloudabi-ports/_obj/distfiles/gmp-6.1.0.tar.xz
checking build system type... Invalid configuration `haswell-pc-linux-gnu': machine `haswell-pc' not recognized
configure: error: /bin/bash /usr/obj/cloudabi-ports/build/0/gmp-6.1.0/config.sub haswell-pc-linux-gnu failed
Traceback (most recent call last):
  File "./build_packages.py", line 55, in <module>
    build_package(package)
  File "./build_packages.py", line 44, in build_package
    catalog.insert(package, version, catalog.package(package, version))
  File "/usr/cloudabi-ports/src/catalog.py", line 446, in package
    package.build()
  File "/usr/cloudabi-ports/src/package.py", line 109, in build
    }, self._lib_depends)
  File "/usr/cloudabi-ports/src/package.py", line 179, in initialize_buildroot
    dep.build()
  File "/usr/cloudabi-ports/src/package.py", line 116, in build
    self._resource_directory))
  File "<string>", line 8, in build
  File "/usr/cloudabi-ports/src/builder.py", line 92, in autoconf
    builddir, os.path.join(self._path, 'configure'), args)
  File "/usr/cloudabi-ports/src/builder.py", line 352, in autoconf
    '--prefix=' + self.get_prefix()] + args)
  File "/usr/cloudabi-ports/src/builder.py", line 460, in run
    ] + command)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['env', '-i', 'AR=/usr/obj/cloudabi-ports/bin/x86_64-unknown-cloudabi-ar', 'CC=/usr/obj/cloudabi-ports/bin/x86_64-unknown-cloudabi-cc', 'CC_FOR_BUILD=/usr/bin/clang-3.7', 'CFLAGS=-O2 -fstack-protector-strong -Werror=implicit-function-declaration -Werror=date-time', 'CXX=/usr/obj/cloudabi-ports/bin/x86_64-unknown-cloudabi-c++', 'CXXFLAGS=-O2 -fstack-protector-strong -Werror=implicit-function-declaration -Werror=date-time', 'CXX_FOR_BUILD=/usr/bin/clang++-3.7', 'NM=/usr/obj/cloudabi-ports/bin/x86_64-unknown-cloudabi-nm', 'OBJDUMP=/usr/obj/cloudabi-ports/bin/x86_64-unknown-cloudabi-objdump', 'PATH=/usr/obj/cloudabi-ports/bin:/usr/obj/cloudabi-ports/bin', 'PERL=/usr/bin/perl', 'PKG_CONFIG=/usr/obj/cloudabi-ports/bin/x86_64-unknown-cloudabi-pkg-config', 'RANLIB=/usr/obj/cloudabi-ports/bin/x86_64-unknown-cloudabi-ranlib', 'STRIP=/usr/obj/cloudabi-ports/bin/x86_64-unknown-cloudabi-strip', '/usr/obj/cloudabi-ports/build/0/gmp-6.1.0/configure', '--host=x86_64-unknown-cloudabi', '--prefix=/sXnLPjhMRwzJweuT', 'gmp_prog_cc_works=yes']' returned non-zero exit status 1
```

**Comment by EdSchouten** [comment]
Oh, wow. I wasn't aware of that. That's... horrible.

The problem is essentially that config.sub and config.guess become out of sync with each other. Let me do a trial run to see whether it's safe to also replace config.guess. We'd better just remove the smartness.

**Comment by EdSchouten** [comment]
It looks like we can also safely replace config.guess. Could you give the latest version of the code a try? Thanks!

**Comment by moreati** [comment]
gmp now builds successfully
